version: '2'

services:
  infuy:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh "./runner.sh"
    environment:
      - ADMIN_USERNAME=infuy
      - ADMIN_PASSWORD=infuy
      - ADMIN_EMAIL=infuy@infuy.com
    volumes:
      - ./infuy:/code
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
  db:
    image: mdillon/postgis:10-alpine
    environment:
      - POSTGRES_DB=infuy
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin